package UserInterfaceSystems;
/**
 * Lead Author(s):
 * 
 * @author Joe DeTone
 * 
 * Other contributors:
 * 
 * References:
 * 
 * Version/date: 0.4 8 DEC 2024
 * 
 * Responsibilities of class:
 * 
 * Provides fields and methods for the LauncherWindow class.
 * 
 * Responsible for displaying the GUI to the user.  UI elements are fed in via a hash map generated by {@code GUIComponets}.
 * All UI elements are accessed in their respective methods by casting types. To understand the casting or element position value
 * used in a component type array, see {@code PanelGenerator}.
 * UI updates are achieved by replacing JPanel field values with JPanels stored in the hash map created by {@code GUIComponents}
 * and calling the needed methods to refresh initial JFrame. This was done to cut down on opening and closer new frames.
 * While the code is far from nice to look at, this method provides a smoother experience for the user.
 * 
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JTextPane;

public class LauncherWindow {
	
	private final JFrame frame = new JFrame();;
	private final HashMap<String, JPanel> launcherPanels = GUIComponents.uiPanelsHashMap();
	private final JPanel characterCreationPanel = (JPanel) launcherPanels.get("Character Creation");
	private final JPanel mechCreationPanel = (JPanel) launcherPanels.get("Mech Creation");
	private final JPanel mechHangarPanel = (JPanel) launcherPanels.get("Mech Hangar");
	private final JPanel combatPanel = (JPanel) launcherPanels.get("Combat");
	private JPanel panel;
	private JPanel titlePanel = new JPanel();
	private JButton launchButton = new JButton();
	private JLabel titleLabel = new JLabel();
	
	/**
	 * Initial frame element. This element is never destroyed, only refreshed as needed.
	 */
	public LauncherWindow() {
		this.frame.setTitle("MECH MASTERS");
		this.frame.setVisible(true);
		this.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.frame.setSize(850, 500);
		this.frame.setResizable(false);
		this.frame.setLocationRelativeTo(null);
		this.frame.getContentPane().setBackground(Color.GRAY);
		this.frame.setLayout(new GridBagLayout());
		this.frame.add(panel = titlePanel);
		
		this.titlePanel.setBackground(Color.GRAY);
		this.titlePanel.setLayout(new BorderLayout());
		this.titlePanel.add(titleLabel, BorderLayout.CENTER);
		this.titlePanel.add(launchButton, BorderLayout.SOUTH);
		
		this.titleLabel.setHorizontalAlignment(JLabel.CENTER);
		this.titleLabel.setText("MECH MASTERS");
		Font titleLabelFont = new Font("DejaVu Sans", Font.BOLD, 60);
		this.titleLabel.setFont(titleLabelFont);
		
		this.launchButton.setText("LAUNCH!");
		this.launchButton.setHorizontalAlignment(JButton.CENTER);
		this.launchButton.setFocusable(false);
	}
	
	/**
	 * Assigns listener to the respective UI element.
	 * @param launcherListener Listener provided by {@code GUIController}
	 */
	public void addCreateLaunchButtonListener(ActionListener launcherListener) {
		this.launchButton.addActionListener(launcherListener);
	}
	
	/**
	 * Assigns listener to the respective UI element.
	 * See .add order in {@code PanelGenerator} for respective element value.
	 * @param createCharacterListener Listener provided by {@code GUIController}
	 */
	public void addCreateCharacterButtonListener(ActionListener createCharacterListener) {
		final int CHARACTER_PANEL_BUTTON_ELEMENT = 2;
		JButton createCharacterButton;
		createCharacterButton = (JButton) characterCreationPanel.getComponent(CHARACTER_PANEL_BUTTON_ELEMENT);
		createCharacterButton.addActionListener(createCharacterListener);
	}
	
	/**
	 * Assigns listener to the respective UI element.
	 * See .add order in {@code PanelGenerator} for respective element value.
	 * @param creatMechListener
	 */
	public void addCreateMechButtonListener(ActionListener creatMechListener) {
		final int MECH_PANEL_BUTTON_ELEMENT = 6;
		JButton createMechButton = (JButton) mechCreationPanel.getComponent(MECH_PANEL_BUTTON_ELEMENT);
		createMechButton.addActionListener(creatMechListener);
	}
	
	/**
	 * Assigns listener to the respective UI element.
	 * See .add order in {@code PanelGenerator} for respective element value.
	 * @param BattleListener
	 */
	public void addCreateBattleButtonListener(ActionListener BattleListener) {
		final int BATTLE_BUTTON_ELEMENT = 0;
		final int BUTTONS_PANEL_ELEMENT = 3;
		JPanel hangarButtonsPanel = (JPanel) mechHangarPanel.getComponent(BUTTONS_PANEL_ELEMENT);
 		JButton createBattleButton = (JButton) hangarButtonsPanel.getComponent(BATTLE_BUTTON_ELEMENT);
		createBattleButton.addActionListener(BattleListener);
	}
	
	/**
	 * Assigns listener to the respective UI element.
	 * See .add order in {@code PanelGenerator} for respective element value.
	 * @param saveGameListener
	 */
	public void addCreateSaveGameButtonListener(ActionListener saveGameListener) {
		final int BUTTON_CONTROL_PANEL_ELEMENT = 3;
		final int SAVE_GAME_BUTTON_ELEMENT = 2;
		JPanel buttonControlPanel = (JPanel) mechHangarPanel.getComponent(BUTTON_CONTROL_PANEL_ELEMENT);
		JButton saveGameButton = (JButton) buttonControlPanel.getComponent(SAVE_GAME_BUTTON_ELEMENT);
		saveGameButton.addActionListener(saveGameListener);
	}
	
	/**
	 * Assigns listener to the respective UI element.
	 * See .add order in {@code PanelGenerator} for respective element value.
	 * @param loadGameListener
	 */
	public void addCreateLoadGameButtonListener(ActionListener loadGameListener) {
		final int BUTTON_CONTROL_PANEL_ELEMENT = 3;
		final int LOAD_GAME_BUTTON_ELEMENT = 3;
		JPanel buttonControlPanel = (JPanel) mechHangarPanel.getComponent(BUTTON_CONTROL_PANEL_ELEMENT);
		JButton loadGameButton = (JButton) buttonControlPanel.getComponent(LOAD_GAME_BUTTON_ELEMENT);
		loadGameButton.addActionListener(loadGameListener);
	}
	
	/**
	 * Assigns listener to the respective UI element.
	 * See .add order in {@code PanelGenerator} for respective element value.
	 * @param attackListener
	 */
	public void addAttackButtonListener(ActionListener attackListener) {
		final int BUTTON_CONTROL_PANEL_ELEMENT = 3;
		final int ATTACK_BUTTON_ELEMENT = 0;
		JPanel buttonControlPanel = (JPanel) combatPanel.getComponent(BUTTON_CONTROL_PANEL_ELEMENT);
		JButton loadGameButton = (JButton) buttonControlPanel.getComponent(ATTACK_BUTTON_ELEMENT);
		loadGameButton.addActionListener(attackListener);
	}
	
//	public void addDefendButtonListener(ActionListener defendListener) {
//		final int BUTTON_CONTROL_PANEL_ELEMENT = 3;
//		final int DEFEND_BUTTON_ELEMENT = 1;
//		JPanel buttonControlPanel = (JPanel) combatPanel.getComponent(BUTTON_CONTROL_PANEL_ELEMENT);
//		JButton loadGameButton = (JButton) buttonControlPanel.getComponent(DEFEND_BUTTON_ELEMENT);
//		loadGameButton.addActionListener(defendListener);
//	}
	
	/**
	 * {@code GUIController} access method.
	 * See .add order in {@code PanelGenerator} for respective element value.
	 * @return Returns String value for player character name as entered by the user in text field.
	 */
	public String getCharacterNameField() {
		final int CHARACTER_NAME_ELEMENT = 1;
		JTextField characterName;
		characterName = (JTextField) characterCreationPanel.getComponent(CHARACTER_NAME_ELEMENT);
		return characterName.getText();
	}
	
	/**
	 * {@code GUIController} access method.
	 * @return Returns selection item from drop down menu as a String.
	 */
	public String getMechTypeField() {
		final int MECH_TYPE_ELEMENT = 2;
		JComboBox<?> comboBox = (JComboBox<?>) mechCreationPanel.getComponent(MECH_TYPE_ELEMENT);
		return (String) comboBox.getSelectedItem();
	}
	
	/**
	 * {@code GUIController} access method.
	 * @return Returns selection item from drop down menu as a String.
	 */
	public String getMechColorField() {
		final int MECH_COLOR_ELEMENT = 4;
		JComboBox<?> comboBox = (JComboBox<?>) mechCreationPanel.getComponent(MECH_COLOR_ELEMENT);
		return (String) comboBox.getSelectedItem();
	}
	
	/**
	 * {@code GUIController} access method.
	 * @return Returns mech name from text field as String.
	 */
	public String getMechNameField() {
		final int MECH_NAME_ELEMENT = 5;
		JTextField mechName;
		mechName = (JTextField) mechCreationPanel.getComponent(MECH_NAME_ELEMENT);
		return mechName.getText();
	}
	
	/**
	 * Governs UI transition to character creation.
	 */
	public void transitionToCharacterCreation() {
		this.frame.remove(this.panel);
		this.frame.add(this.panel = characterCreationPanel);
		this.frame.setLayout(new GridBagLayout());
		this.frame.revalidate();
		this.frame.repaint();
	}
	
	/**
	 * Governs UI transition to mech creation.
	 */
	public void transitionToMechCreation() {
		this.frame.remove(this.panel);
		this.frame.add(this.panel = mechCreationPanel);
		this.frame.setLayout(new GridBagLayout());
		this.frame.revalidate();
		this.frame.repaint();
	}
	
	/**
	 * Governs UI transition to hanger display. Provided arguments are displayed on screen for the player to see.
	 * Values are provided by the UI controller class and only needs to be called once per program start.
	 * Otherwise, use {@code transitionBackToHangar} to return the display to the hangar.
	 * @param playerName String value supplied by UI controller.
	 * @param mechName String value supplied by UI controller.
	 * @param mechColor String value supplied by UI controller.
	 * @param mechType String value supplied by UI controller.
	 * @param mechArmorAmount String value supplied by UI controller.
	 */
	public void transitionToMechHangar(String playerName, String mechName, String mechColor, 
										String mechType, String mechArmorAmount) {
		this.frame.remove(this.panel);
		this.frame.setLayout(new BorderLayout());
		JPanel tempPanel;
		JLabel tempLabel;
		
		tempPanel = (JPanel) mechHangarPanel.getComponent(1);
		tempLabel = (JLabel) tempPanel.getComponent(0);
		tempLabel.setText(playerName);
		tempLabel = (JLabel) tempPanel.getComponent(2);
		tempLabel.setText(mechName);
		tempLabel = (JLabel) tempPanel.getComponent(3);
		tempLabel.setText(mechColor);
		tempLabel = (JLabel) tempPanel.getComponent(5);
		tempLabel.setText(mechType);
		tempLabel = (JLabel) tempPanel.getComponent(6);
		tempLabel.setText(mechArmorAmount);
		
		tempPanel = (JPanel) combatPanel.getComponent(1);
		tempLabel = (JLabel) tempPanel.getComponent(0);
		tempLabel.setText(playerName);
		tempLabel = (JLabel) tempPanel.getComponent(2);
		tempLabel.setText(mechName);
		tempLabel = (JLabel) tempPanel.getComponent(3);
		tempLabel.setText(mechColor);
		tempLabel = (JLabel) tempPanel.getComponent(5);
		tempLabel.setText(mechType);
		tempLabel = (JLabel) tempPanel.getComponent(6);
		tempLabel.setText(mechArmorAmount);
		
		this.frame.add(this.panel = mechHangarPanel, BorderLayout.CENTER);
		this.frame.revalidate();
		this.frame.repaint();
	}
	
	/**
	 * Governs UI transition back to hangar display.
	 */
	public void transitionBackToHangar() {
		this.frame.remove(this.panel);
		this.frame.add(this.panel = mechHangarPanel, BorderLayout.CENTER);
		this.frame.revalidate();
		this.frame.repaint();
	}
	
	/**
	 * Governs UI transition to combat encounter display. Argument values are supplied via UI controller.
	 * Values are generated by {@code CombatMechanics}
	 * @param enemyName String value supplied by UI controller.
	 * @param mechName String value supplied by UI controller.
	 * @param mechColor String value supplied by UI controller.
	 * @param mechType String value supplied by UI controller.
	 * @param mechArmorAmount String value supplied by UI controller.
	 */
	public void transitionToBattle(String enemyName, String mechName, String mechColor, 
									String mechType, String mechArmorAmount) {
		this.frame.remove(this.panel);
		
		JPanel tempPanel;
		JLabel tempLabel;
		
		tempPanel = (JPanel) combatPanel.getComponent(2);
		tempLabel = (JLabel) tempPanel.getComponent(0);
		tempLabel.setText(enemyName);
		tempLabel = (JLabel) tempPanel.getComponent(2);
		tempLabel.setText(mechName);
		tempLabel = (JLabel) tempPanel.getComponent(3);
		tempLabel.setText(mechColor);
		tempLabel = (JLabel) tempPanel.getComponent(5);
		tempLabel.setText(mechType);
		tempLabel = (JLabel) tempPanel.getComponent(6);
		tempLabel.setText(mechArmorAmount);
		
		this.frame.add(this.panel = combatPanel, BorderLayout.CENTER);
		this.frame.revalidate();
		this.frame.repaint();
	}
	
	/**
	 * Error display method. See {@code PanelGenerator} .add order for UI element value.
	 * @param errorState
	 */
	public void updateCharacterCreationNameError(boolean errorState) {
		final int NAME_ERROR_ELEMENT = 3;
		JLabel errorLabel;
		errorLabel = (JLabel) characterCreationPanel.getComponent(NAME_ERROR_ELEMENT);
		errorLabel.setVisible(errorState);
		this.panel.revalidate();
		this.panel.repaint();
	}
	
	/**
	 * Error display method. See {@code PanelGenerator} .add order for UI element value.
	 * @param errorState {@code True}, show error message.
	 */
	public void updateMechCreationNameError(boolean errorState) {
		final int NAME_ERROR_ELEMENT = 7;
		JLabel errorLabel;
		errorLabel = (JLabel) mechCreationPanel.getComponent(NAME_ERROR_ELEMENT);
		errorLabel.setVisible(errorState);
		this.panel.revalidate();
		this.panel.repaint();
	}
	
	/**
	 * Updates the combat text being displayed for the player and enemy based on arguments received from the controller.
	 * @param enemySpeech String value supplied by UI controller.
	 * @param playerSpeech String value supplied by UI controller.
	 */
	public void updateCombatText(String enemySpeech, String playerSpeech) {
		final int TEXT_RENDER_PANEL_ELEMENT = 0;
		final int ENEMY_SPEECH_ELEMENT = 1;
		final int PLAYER_SPEECH_ELEMENT = 3;
		JPanel tempPanel;
		JTextPane tempPane;
		
		tempPanel = (JPanel) combatPanel.getComponent(TEXT_RENDER_PANEL_ELEMENT);
		tempPane = (JTextPane) tempPanel.getComponent(ENEMY_SPEECH_ELEMENT);
		tempPane.setText(enemySpeech);
		tempPane = (JTextPane) tempPanel.getComponent(PLAYER_SPEECH_ELEMENT);
		tempPane.setText(playerSpeech);
	}
	
	/**
	 * Updates the display for the player's remaining armor amount after an attack action event.
	 * @param mechArmorAmount String value supplied by UI controller.
	 */
	public void updateMechArmorAmountCombatDisplayPlayer(String mechArmorAmount) {
		final int DATA_DISPLAY_LEFT_ELEMENT = 1;
		final int LABEL_MECH_ARMOR_AMOUNT = 6;
		JPanel tempPanel;
		JLabel tempLabel;
		
		tempPanel = (JPanel) combatPanel.getComponent(DATA_DISPLAY_LEFT_ELEMENT);
		tempLabel = (JLabel) tempPanel.getComponent(LABEL_MECH_ARMOR_AMOUNT);
		tempLabel.setText(mechArmorAmount);
		this.panel.revalidate();
		this.panel.repaint();
	}
	
	/**
	 * Updates the display for the enemy's remaining armor amount after an attack action event.
	 * @param mechArmorAmount String value supplied by UI controller.
	 */
	public void updateMechArmorAmountCombatDisplayEnemy(String mechArmorAmount) {
		final int DATA_DISPLAY_RIGHT_ELEMENT = 2;
		final int LABEL_MECH_ARMOR_AMOUNT = 6;
		JPanel tempPanel;
		JLabel tempLabel;
		
		tempPanel = (JPanel) combatPanel.getComponent(DATA_DISPLAY_RIGHT_ELEMENT);
		tempLabel = (JLabel) tempPanel.getComponent(LABEL_MECH_ARMOR_AMOUNT);
		tempLabel.setText(mechArmorAmount);
		this.panel.revalidate();
		this.panel.repaint();
	}
	
	/**
	 * Restores the display for the player's armor amount value when returning to the hangar display.
	 * @param mechArmorAmount String value supplied by UI controller.
	 */
	public void updateMechArmorAmountHangarDisplay(String mechArmorAmount) {
		final int DATA_DISPLAY_LEFT_ELEMENT = 1;
		final int LABEL_MECH_ARMOR_AMOUNT = 6;
		JPanel tempPanel;
		JLabel tempLabel;
		
		tempPanel = (JPanel) mechHangarPanel.getComponent(DATA_DISPLAY_LEFT_ELEMENT);
		tempLabel = (JLabel) tempPanel.getComponent(LABEL_MECH_ARMOR_AMOUNT);
		tempLabel.setText(mechArmorAmount);
		this.panel.revalidate();
		this.panel.repaint();
	}
	
	/**
	 * Updates the JTextPane text with the out come of the combat event.
	 * @param inputMessage String value supplied by UI controller.
	 */
	public void updateOutComeMessage(String inputMessage) {
		final int TEXT_RENDER_PANEL_ELEMENT = 0;
		final int JTEXT_PANE_ELEMENT = 0;
		JPanel tempPanel;
		JTextPane tempPane;
		
		tempPanel = (JPanel) mechHangarPanel.getComponent(TEXT_RENDER_PANEL_ELEMENT);
		tempPane = (JTextPane) tempPanel.getComponent(JTEXT_PANE_ELEMENT);
		tempPane.setText(inputMessage);
	}
}